name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Generate Prisma Client
        working-directory: backend
        run: npx prisma generate

      - name: Build TypeScript
        working-directory: backend
        run: npm run build

      - name: Create deployment package
        working-directory: backend
        run: |
          mkdir -p deploy
          cp -r dist/* deploy/
          cp package.json package-lock.json deploy/
          cp -r prisma deploy/
          # Copy generated Prisma client
          mkdir -p deploy/node_modules/.prisma
          cp -r node_modules/.prisma/* deploy/node_modules/.prisma/ || true

      - name: Install production dependencies
        working-directory: backend/deploy
        run: |
          npm ci --only=production
          npx prisma generate

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: site-safety-login
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend/deploy